steps:
  # Step 1: Terraform Init & Plan (Always runs for PRs and Merges)
  - id: 'tf-plan'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export TF_LOG=INFO
        base_dir="environments/dev/"
       
        for dir in iam networking storage compute database monitoring containers GKE; do
          echo "--- Processing: $dir ---"
          echo "--- Initializing & Planning: $dir ---"
          terraform -chdir="$base_dir$dir" init -input=false
          terraform -chdir="$base_dir$dir" plan -input=false -var-file="../../../terraform.tfvars"
        done

  # Step 2: Terraform Apply (Runs ONLY when merged to main)
  - id: 'tf-apply'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Condition check: If _PR_NUMBER is NOT empty, we are in a PR. Exit early.
        if [ ! -z "$_PR_NUMBER" ]; then
          echo "This is a Pull Request (#$_PR_NUMBER). Skipping Apply."
          exit 0
        fi

        # Condition check: Only apply if we are on the main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "Current branch is $BRANCH_NAME. Skipping Apply."
          exit 0
        fi

        base_dir="environments/dev/"
        for dir in iam networking storage compute database monitoring containers GKE; do
          echo "--- Applying Changes: $dir ---"
          terraform -chdir="$base_dir$dir" apply -auto-approve -input=false -var-file="../../../terraform.tfvars"
        done
        for dir in containers GKE  compute database monitoring storage iam networking; do
          echo "--- deleting Changes: $dir ---"
          terraform -chdir="$base_dir$dir" destroy -auto-approve -input=false -var-file="../../../terraform.tfvars"        
        done
        
options:
  logging: CLOUD_LOGGING_ONLY
