apiVersion: v1
kind: Service
metadata:
  name: web-app-lb-service
spec:
  type: LoadBalancer 
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80         # The port the public sees
      targetPort: 8080 # The port your Python app listens on
